# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /users/u31/sol/vhdl_guitar_pedal/hdl/vhdl_guitar_pedal.srcs/sources_1/ip/xfft_0/xfft_0.xci
# IP: The module: 'xfft_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /users/u31/sol/vhdl_guitar_pedal/hdl/vhdl_guitar_pedal.gen/sources_1/ip/xfft_0/xfft_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xfft_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /users/u31/sol/vhdl_guitar_pedal/hdl/vhdl_guitar_pedal.srcs/sources_1/ip/xfft_0/xfft_0.xci
# IP: The module: 'xfft_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /users/u31/sol/vhdl_guitar_pedal/hdl/vhdl_guitar_pedal.gen/sources_1/ip/xfft_0/xfft_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xfft_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
