#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2025.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Jun 18 03:52:05 EDT 2026
# SW Build 6140274 on Wed May 21 22:58:25 MDT 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim guitar_pedal_tb_behav -key {Behavioral:sim_1:Functional:guitar_pedal_tb} -tclbatch guitar_pedal_tb.tcl -log simulate.log"
xsim guitar_pedal_tb_behav -key {Behavioral:sim_1:Functional:guitar_pedal_tb} -tclbatch guitar_pedal_tb.tcl -log simulate.log

