set_property SRC_FILE_INFO {cfile:/home/Sol/vhdl_guitar_pedal/hdl/vhdl_guitar_pedal.gen/sources_1/ip/xfft_0/xfft_0/xfft_0_in_context.xdc rfile:../../../../../vhdl_guitar_pedal.gen/sources_1/ip/xfft_0/xfft_0/xfft_0_in_context.xdc id:1 order:EARLY scoped_inst:polar_fft_0/forward_fft} [current_design]
set_property SRC_FILE_INFO {cfile:/home/Sol/vhdl_guitar_pedal/hdl/vhdl_guitar_pedal.gen/sources_1/ip/xfft_0/xfft_0/xfft_0_in_context.xdc rfile:../../../../../vhdl_guitar_pedal.gen/sources_1/ip/xfft_0/xfft_0/xfft_0_in_context.xdc id:2 order:EARLY scoped_inst:rectangular_ifft_0/inverse_fft} [current_design]
set_property SRC_FILE_INFO {cfile:/home/Sol/vhdl_guitar_pedal/hdl/vhdl_guitar_pedal.gen/sources_1/ip/clk_wiz_0/clk_wiz_0/clk_wiz_0_in_context.xdc rfile:../../../../../vhdl_guitar_pedal.gen/sources_1/ip/clk_wiz_0/clk_wiz_0/clk_wiz_0_in_context.xdc id:3 order:EARLY scoped_inst:m_clk} [current_design]
set_property SRC_FILE_INFO {cfile:/home/Sol/vhdl_guitar_pedal/hdl/vhdl_guitar_pedal.gen/sources_1/ip/cordic_0/cordic_0/cordic_0_in_context.xdc rfile:../../../../../vhdl_guitar_pedal.gen/sources_1/ip/cordic_0/cordic_0/cordic_0_in_context.xdc id:4 order:EARLY scoped_inst:polar_fft_0/rectangular_to_polar} [current_design]
set_property SRC_FILE_INFO {cfile:/home/Sol/vhdl_guitar_pedal/hdl/vhdl_guitar_pedal.gen/sources_1/ip/cordic_1/cordic_1/cordic_1_in_context.xdc rfile:../../../../../vhdl_guitar_pedal.gen/sources_1/ip/cordic_1/cordic_1/cordic_1_in_context.xdc id:5 order:EARLY scoped_inst:rectangular_ifft_0/polar_to_rectangular} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins polar_fft_0/forward_fft/aclk]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells polar_fft_0/forward_fft]
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins rectangular_ifft_0/inverse_fft/aclk]
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {rectangular_ifft_0/inverse_fft[*]}]
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name CLK100MHZ [get_ports CLK100MHZ]
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name m_clk/clk_out1 -source [get_pins m_clk/clk_in1] -edges {1 2 3} -edge_shift {0.000 0.000 0.000} [get_pins m_clk/clk_out1]
set_property src_info {type:SCOPED_XDC file:3 line:3 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name m_clk/clk_out2 -source [get_pins m_clk/clk_in1] -edges {1 2 3} -edge_shift {0.000 15.351 30.702} [get_pins m_clk/clk_out2]
set_property src_info {type:SCOPED_XDC file:3 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports CLK100MHZ]
set_property src_info {type:SCOPED_XDC file:3 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports CLK100MHZ]
set_property src_info {type:SCOPED_XDC file:3 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells m_clk]
set_property src_info {type:SCOPED_XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 1000 [get_pins polar_fft_0/rectangular_to_polar/aclk]
set_property src_info {type:SCOPED_XDC file:4 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells polar_fft_0/rectangular_to_polar]
set_property src_info {type:SCOPED_XDC file:5 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 1000 [get_pins rectangular_ifft_0/polar_to_rectangular/aclk]
set_property src_info {type:SCOPED_XDC file:5 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells rectangular_ifft_0/polar_to_rectangular]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells polar_fft_0/forward_fft]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {rectangular_ifft_0/inverse_fft[*]}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells m_clk]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells polar_fft_0/rectangular_to_polar]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells rectangular_ifft_0/polar_to_rectangular]
