# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/Sol/vhdl_guitar_pedal/hdl/vhdl_guitar_pedal.srcs/sources_1/ip/cordic_0/cordic_0.xci
# IP: The module: 'cordic_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/Sol/vhdl_guitar_pedal/hdl/vhdl_guitar_pedal.gen/sources_1/ip/cordic_0/cordic_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cordic_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/Sol/vhdl_guitar_pedal/hdl/vhdl_guitar_pedal.srcs/sources_1/ip/cordic_0/cordic_0.xci
# IP: The module: 'cordic_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/Sol/vhdl_guitar_pedal/hdl/vhdl_guitar_pedal.gen/sources_1/ip/cordic_0/cordic_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cordic_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
